### PR TITLE
Java 8 follow-up changes

### LINKED ISSUE #2501: Build failure with Java 21
Gson fails to build with Java 21, for two reasons:

1. The source/target level 7 is no longer supported:

        [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project gson: Fatal error compiling: error: release version 7 not supported -> [Help 1]

2. If the level is changed to 8, compiler warnings appear and break the build:

        [INFO] -------------------------------------------------------------
        [WARNING] COMPILATION WARNING :
        [INFO] -------------------------------------------------------------
        [WARNING] gson/src/main/java/com/google/gson/internal/$Gson$Types.java:[500,24] non-transient instance field of a serializable class declared with a non-serializable type
        [WARNING] gson/src/main/java/com/google/gson/internal/$Gson$Types.java:[501,24] non-transient instance field of a serializable class declared with a non-serializable type
        [WARNING] gson/src/main/java/com/google/gson/internal/$Gson$Types.java:[502,26] non-transient instance field of a serializable class declared with an array having a non-serializable base component type java.lang.reflect.Type
        [WARNING] gson/src/main/java/com/google/gson/internal/$Gson$Types.java:[567,24] non-transient instance field of a serializable class declared with a non-serializable type
        [WARNING] gson/src/main/java/com/google/gson/internal/$Gson$Types.java:[601,24] non-transient instance field of a serializable class declared with a non-serializable type
        [WARNING] gson/src/main/java/com/google/gson/internal/$Gson$Types.java:[602,24] non-transient instance field of a serializable class declared with a non-serializable type
        [INFO] 6 warnings
        [INFO] -------------------------------------------------------------
        [INFO] -------------------------------------------------------------
        [ERROR] COMPILATION ERROR :
        [INFO] -------------------------------------------------------------
        [ERROR] gson/src/main/java/com/google/gson/internal/$Gson$Types.java: warnings found and -Werror specified
        [INFO] 1 error
        [INFO] -------------------------------------------------------------

### PR DESCRIPTION
**Pull request by Marcono1234**
### Purpose
Follow-up for #2744
Resolves #2501 (building with JDK 21 is now possible without any custom configuration)

### Description
Regarding the Error Prone warnings:
For the `final` variable warnings, it seems some of those variables were made `final` intentionally, without the compiler requiring it. But for consistency I removed the `final` from them as well.

### Checklist

- [ ] New code follows the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)\
  This is automatically checked by `mvn verify`, but can also be checked on its own using `mvn spotless:check`.\
  Style violations can be fixed using `mvn spotless:apply`; this can be done in a separate commit to verify that it did not cause undesired changes.
- [ ] If necessary, new public API validates arguments, for example rejects `null`
- [ ] New public API has Javadoc
    - [ ] Javadoc uses `@since $next-version$`  
      (`$next-version$` is a special placeholder which is automatically replaced during release)
- [ ] If necessary, new unit tests have been added  
  - [ ] Assertions in unit tests use [Truth](https://truth.dev/), see existing tests
  - [ ] No JUnit 3 features are used (such as extending class `TestCase`)
  - [ ] If this pull request fixes a bug, a new test was added for a situation which failed previously and is now fixed
- [x] `mvn clean verify javadoc:jar` passes without errors

### CODE REVIEW

File: gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java [hunk 1]
```diff
@@ -43,13 +43,7 @@
...
 public final class LinkedTreeMap<K, V> extends AbstractMap<K, V> implements Serializable {
   @SuppressWarnings({"unchecked", "rawtypes"}) // to avoid Comparable<Comparable<Comparable<...>>>
-  private static final Comparator<Comparable> NATURAL_ORDER =
-      new Comparator<Comparable>() {
-        @Override
-        public int compare(Comparable a, Comparable b) {
-          return a.compareTo(b);
-        }
-      };
+  private static final Comparator<Comparable> NATURAL_ORDER = Comparator.naturalOrder();
```
Comment (Marcono1234) [inline gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java:46]: The code below performs identity checks (`== NATURAL_ORDER`) on this, but I hope this should be fine.

File: gson/src/main/java/com/google/gson/internal/NonNullElementWrapperList.java [hunk 2]
```diff
@@ -107,6 +109,16 @@ public int lastIndexOf(Object o) {
     return delegate.lastIndexOf(o);
   }
 
+  @Override
+  public Spliterator<E> spliterator() {
+    return delegate.spliterator();
+  }
```
Comment (Marcono1234) [inline gson/src/main/java/com/google/gson/internal/NonNullElementWrapperList.java:115]: I have also overridden `spliterator` since the `ArrayList` implementation might be more efficient than the default `List` one.

Though I am not completely sure if this is really necessary; it seems the default `List#spliterator` uses a specialized implementation if the list if `RandomAccess` (which is the case here), and that implementation looks quite similar to the `ArrayList` one.

Comment (Marcono1234) [reply gson/src/main/java/com/google/gson/internal/NonNullElementWrapperList.java]: Obsolete: Had to remove these overrides again because the minimum Android API level we support does not have them yet.

File: .github/workflows/build.yml [hunk 3]
```diff
@@ -10,12 +10,7 @@ jobs:
     name: "Build on JDK ${{ matrix.java }}"
     strategy:
       matrix:
-        java: [ 11, 17 ]
-        # Custom JDK 21 configuration
-        include:
-          - java: 21
-            # Disable Enforcer check which (intentionally) prevents using JDK 21 for building
-            extra-mvn-args: -Denforcer.fail=false
+        java: [ 11, 17, 21 ]
```
Comment (eamonnmcmanus) [inline .github/workflows/build.yml:13]: Yay!

**Review by eamonnmcmanus — APPROVED** [review]
This is great, thanks! Look at all those `final` modifiers deleted.
