### PR TITLE
Disallow `JsonObject` `Entry.setValue(null)`

### LINKED ISSUE #1771: JsonObject.entrySet() Entry.setValue(...) does not prevent null values
The Map.Entry objects in the Set returned by `JsonObject.entrySet()` do not validate the value passed to their `Entry.setValue(...)` method, allowing Java `null`s. This can cause runtime exceptions when the user of the JsonObject later expects that the values returned by JsonObject are never `null`:
```java
JsonObject jsonObject = new JsonObject();
jsonObject.addProperty("test", 1);
jsonObject.entrySet().iterator().next().setValue(null);

System.out.println("has=" + jsonObject.has("test"));
jsonObject.getAsJsonPrimitive("test").toString(); // NullPointerException
```

The Map.Entry objects should instead throw a NullPointerException when their `setValue(...)` method is called with `null` (as permitted by the [documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.Entry.html#setValue(V))).

### PR DESCRIPTION
**Pull request by Marcono1234**
Fixes #1771

`JsonObject` is supposed to only contain non-`null` values (JSON null is modelled by `JsonNull`), however the method `Entry.setValue` from the entries obtained by `entrySet()` did not enforce this.

### CODE REVIEW

File: gson/src/test/java/com/google/gson/JsonObjectTest.java [hunk 1]
```diff
@@ -200,5 +210,92 @@ public void testKeySet() {
...
+
+    // Remove keys one by one
+    for (int i = a.size(); i >= 1; i--) {
+      assertTrue(iterator.hasNext());
+      assertEquals(expectedKeys.getFirst(), iterator.next());
+      iterator.remove();
+      expectedKeys.removeFirst();
+
+      assertEquals(i - 1, a.size());
+      // Note: Must wrap in ArrayList because Deque implementations do not implement `equals`
```
Comment (eamonnmcmanus) [inline gson/src/test/java/com/google/gson/JsonObjectTest.java:230]: Maybe move this comment before line 219, since that's the first time you compare `expectedKeys`.

**Review by eamonnmcmanus — CHANGES_REQUESTED** [review]
LGTM. One very minor suggestion.

**Comment by Marcono1234** [comment]
Nevermind, sorry. I completely overlooked that `JsonObject` (and also `JsonArray`) implicitly converts `null` to `JsonNull`. Maybe it would make sense to do the same here as well? (and also document this conversion in the `JsonObject` class documentation)

That could still be implemented in a reasonably clean way by having a `V nullReplacement` field in `LinkedTreeMap`. For the regular map usage its value would be `null` but for `JsonObject` it would be `JsonNull.INSTANCE`.
Though in case we every want to migrate from `LinkedTreeMap` to a standard JDK class, that would make migration more difficult (or impossible), but so would `null` prevention (but there it would not break the behavior).

**Comment by Marcono1234** [comment]
On the other hand, such implicit conversion might be unexpected for `Map.Entry`, especially when the code working with it does not know that it originally came from a `JsonObject`.

So throwing a `NullPointerException` as originally proposed by this PR might be a better solution.

I have adjusted the comments as you have requested.

**Review by eamonnmcmanus — APPROVED** [review]
All those booleans make me a _little_ unhappy. What would you think of replacing the new `LinkedTreeMap` constructor with a static factory method `LinkedTreeMap.withoutNullValues()` and introducing a nested subclass `private static class NoNullValues<K, V> extends LinkedTreeMap<K, V>`? Then the main `LinkedTreeMap` could call a no-op `checkNullValue` method and the subclass could override that to reject nulls. `NoNullValues` could have its own `Node` subclass (which can also be called `Node`) that rejects `setValue(null)`. `new Node<>(a, b, c, d)` would have to become `newNode(a, b, c, d)` of course.

**Review by eamonnmcmanus — COMMENTED** [review]
Another idea:
Instead of forbidding `Entry.setValue(null)`, could we arrange for `null` to be replaced by `JsonNull.INSTANCE` in the `JsonObject` case? That looks as if it would be more consistent, since `jsonObject.add(property, null)` has that effect already. We could have a new `LinkedTreeMap` constructor that takes a value of type `V` to be used in place of `null`. `Node.setValue(null)` would replace `null` by this value. The value would itself be `null` for the other two uses of `LinkedTreeMap`.

File: gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java [hunk 2]
```diff
@@ -69,12 +81,15 @@ public LinkedTreeMap() {
    *
    * @param comparator the comparator to order elements with, or {@code null} to
    *     use the natural ordering.
+   * @param allowNullValues whether {@code null} is allowed as entry value
    */
   @SuppressWarnings({ "unchecked", "rawtypes" }) // unsafe! if comparator is null, this assumes K is comparable
-  public LinkedTreeMap(Comparator<? super K> comparator) {
+  public LinkedTreeMap(Comparator<? super K> comparator, boolean allowNullValues) {
```
Comment (eamonnmcmanus) [inline gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java:87]: This is an incompatible change, for client code that might be calling `new LinkedTreeMap<>(comparator)` directly. Of course it's an `.internal.` class, so code shouldn't be doing that. I find that Google's codebase has a few places where people _are_ constructing `LinkedTreeMap`, but none where they are calling the `(Comparator)` constructor. So I think we could actually just delete that constructor and hardcode the use of natural ordering. That would allow considerable simplification of the `find` method.

**Comment by Marcono1234** [comment]
> All those booleans make me a _little_ unhappy. What would you think of replacing the new `LinkedTreeMap` constructor with a static factory method `LinkedTreeMap.withoutNullValues()` and introducing a nested subclass `private static class NoNullValues<K, V> extends LinkedTreeMap<K, V>`?

I think having a separate subclass and factory methods for nodes might make this more complex than the `boolean` field approach. But you decide.

> Another idea:
> Instead of forbidding `Entry.setValue(null)`, could we arrange for `null` to be replaced by `JsonNull.INSTANCE` in the `JsonObject` case?

That is what I mentioned in https://github.com/google/gson/pull/2167#issuecomment-1206933345, but as mentioned in https://github.com/google/gson/pull/2167#issuecomment-1207199942 below it, that might not be a good idea. For example when code only obtains a `Map.Entry<String, JsonElement>` (or worse `Entry<String, ?>`, though that is a bit unlikely) without knowing that it came from a `JsonObject` and then calls `setValue(null)`. The contract of `setValue` allows throwing a `NullPointerException`, but it does not mention any implicit value conversion.
My main intention here was to prevent users from breaking invariants of `JsonObject`; I assume the case where a user intentionally calls `setValue(null)` is rather rare (and they could just manually call it with `JsonNull`).

**Comment by Marcono1234** [comment]
@eamonnmcmanus, do you think the current implementation of this pull request is fine or do you want it to be changed (see comment above)?
If you want I can adjust the `entrySet()` documentation to mention that the entries adhere to the standard `Map.Entry` behavior and no implicit `null` conversion is performed.

File: gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java (hunk 2 above)
Comment (Marcono1234) [reply gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java:87]: It looks like other projects [are using `LinkedTreeMap` as well](https://sourcegraph.com/search?q=context:global+new+LinkedTreeMap&patternType=standard), though they don't seem to use that constructor either. Should I add it back nonetheless?

> So I think we could actually just delete that constructor and hardcode the use of natural ordering. That would allow considerable simplification of the `find` method.

Sounds in general reasonable to me, but I am not sure whether that should be part of this pull request.

Comment (eamonnmcmanus) [reply gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java:87]: OK, we can do that as a follow-on.

**Comment by eamonnmcmanus** [comment]
OK, I think this is fine as it is. I may send another PR to delete the `LinkedTreeMap(Comparator)` constructor.
