### PR TITLE
Make JsonElement conversion methods more consistent and fix javadoc

### LINKED ISSUE #1364: Crashes when using the class JsonPrimitive.
**gson Version:** 2.7
**Operating System:** Ubuntu 16.04.4 LTS, McOs High Sierra (version 10.13.5)
**Machine:** single machine (laptop)
**Junit version:** 4.12

### Steps to reproduce
Please run the attached test suite for the class com.google.gson.JsonPrimitive.

[JsonPrimitiveTestSuite.txt](https://github.com/google/gson/files/2242144/JsonPrimitiveTestSuite.txt)

### Context:
The tests I provided come from a static analysis prototype I have been working on as part of a research project. The tool analyses a specified dependency of a project to identify risky API calls which may potentially lead to runtime exceptions. Runtime exceptions may occur either because 1) an API is lacking sufficient documentation, or 2) usage of the API does not conform to the specification, or 3) API wrapper does not indicate the API specification as part of its own specification. The prototype then automatically generates test cases which show how such exceptions may be triggered.

I have been evaluating the tool on various open source projects. In the case of `Gson-2.7`, `JDK API` calls are analyzed. Each provided test case triggers a unique crash due to how data are forwarded to the JDK APIs (e.g. `Short.parseShort(...)`).

### Possible fixes
Before calling the JDK APIs, there should be some checks on the forwarded values.

### LINKED ISSUE #1908: JavaDoc bug in JsonArray and JsonElement classes
The JavaDoc description of `getAsDouble` method in `JsonArray` and `JsonElement` classes states that the method throws “_ClassCastException if the element is of not a JsonPrimitive and is not a valid double value_.” However, it actually throws an `UnsupportedOperationException` if the element is not a `JsonPrimitive` type such as `JsonObject`. Whereas, it throws a `NumberFormatException` if the element is not a valid double value such as string. The behavior is the same for `getAsInt` and `getAsLong` methods.

The JavaDoc description of `getAsBoolean` method in `JsonArray` and `JsonElement` classes states that the method throws “_ClassCastException if the element is of not a JsonPrimitive and is not a valid boolean value._” However, it actually throws an `UnsupportedOperationException` if the element is not a `JsonPrimitive` type such as `JsonObject`. Whereas, it does not throw any exception (returns `false`) if the element is not a valid boolean value such as string and double. It is not clear though whether the bug is in the documented behavior or the implemented behavior. The behavior is the same for the `getAsString` method.

### PR DESCRIPTION
**Pull request by Marcono1234**
Resolves #1364
Resolves #1908

Fixes issues with the `JsonElement` documentation which erroneously claimed that a `ClassCastException` is thrown when conversion methods such as `getAsInt()` fail, while actually none of the methods except for `getAsNumber()` previously threw a `ClassCastException`.
Have adjusted `getAsNumber()` to throw `UnsupportedOperationException` for consistency.

Also fixes that `JsonPrimitive.getAsChar()` was throwing `StringIndexOutOfBoundsException`; now an `UnsupportedOperationException` is thrown.

### CODE REVIEW

File: gson/src/main/java/com/google/gson/JsonPrimitive.java [hunk 1]
```diff
@@ -95,9 +95,10 @@ public boolean isBoolean() {
   }
 
   /**
-   * convenience method to get this element as a boolean value.
-   *
-   * @return get this element as a primitive boolean value.
+   * Convenience method to get this element as a boolean value.
+   * If this primitive {@linkplain #isBoolean() is not a boolean}, the string value
+   * is parsed using {@link Boolean#parseBoolean(String)}. This means {@code "true"} (ignoring
+   * case) is considered {@code true} and any other value is considered {@code false}.
```
Comment (eamonnmcmanus) [inline gson/src/main/java/com/google/gson/JsonPrimitive.java:101]: Well that's pretty terrible. But I suppose we're stuck with it.

File: gson/src/main/java/com/google/gson/JsonPrimitive.java [hunk 2]
```diff
@@ -137,108 +145,102 @@ public boolean isString() {
...
     }
+    throw new AssertionError("Unexpected value type: " + value.getClass());
   }
 
   /**
-   * convenience method to get this element as a primitive double.
-   *
-   * @return get this element as a primitive double.
-   * @throws NumberFormatException if the value contained is not a valid double.
+   * @throws NumberFormatException {@inheritDoc}
```
Comment (eamonnmcmanus) [inline gson/src/main/java/com/google/gson/JsonPrimitive.java:162]: I don't think you need this. Just leaving out the doc comment altogether should have the same effect.

**Review by eamonnmcmanus — CHANGES_REQUESTED** [review]
This seems like a great change, thanks! I agree that the change in exceptions for `getAsNumber()` is more consistent and very unlikely to cause problems.

Just some small comments.

File: gson/src/main/java/com/google/gson/JsonPrimitive.java (hunk 1 above)
Comment (Marcono1234) [reply gson/src/main/java/com/google/gson/JsonPrimitive.java:101]: Yeah..., I had created #1775 for that in the past (which also covers the type adapter for `Boolean`). Maybe we can revisit this behavior at some point. Do you think I should omit this detailed documentation here to make it easier to change this behavior in the future? Currently the behavior is simply undocumented.

File: gson/src/main/java/com/google/gson/JsonPrimitive.java (hunk 2 above)
Comment (Marcono1234) [reply gson/src/main/java/com/google/gson/JsonPrimitive.java:162]: It looks like javadoc does not inherit the documented exceptions in that case. So either there has to be a `@throws`, or I add a `throws NumberFormatException` to the method signature. What do you prefer?

File: gson/src/main/java/com/google/gson/JsonArray.java [hunk 3]
```diff
@@ -202,195 +207,183 @@ public Iterator<JsonElement> iterator() {
...
    */
   public JsonElement get(int i) {
     return elements.get(i);
   }
 
+  private JsonElement getAsSingleElement() {
+    if (elements.size() == 1) {
+      return elements.get(0);
+    }
+    throw new IllegalStateException();
```
[the remark this answers is not in the document]
Comment (Marcono1234) [reply gson/src/main/java/com/google/gson/JsonArray.java]: Have also added a test for this because this was apparently not covered previously.

File: gson/src/main/java/com/google/gson/JsonPrimitive.java (hunk 2 above)
Comment (eamonnmcmanus) [reply gson/src/main/java/com/google/gson/JsonPrimitive.java:162]: Oh, I think I've seen this before. The specified behaviour is that exception comments are only copied for exceptions that are declared in the `throws` clause. So what you have here is right. Sorry for the distraction.

File: gson/src/main/java/com/google/gson/JsonPrimitive.java (hunk 1 above)
Comment (eamonnmcmanus) [reply gson/src/main/java/com/google/gson/JsonPrimitive.java:101]: No, the current behaviour is unfortunate, but I think changing it would be too incompatible. So documenting it looks like the right thing to do.

**Review by eamonnmcmanus — APPROVED** [review]
