### PR TITLE
fix #680 - make RuntimeTypeAdapterFactory null-safe

### LINKED ISSUE #680: RuntimeTypeAdapterFactory not null-safe
`RuntimeTypeAdapterFactory` creates a `TypeAdapter` that is not null-safe. This shows up when the adapted-type is the property of another object. Test below:

    public void testSerializeWrappedNullValue() {
      TypeAdapterFactory billingAdapter = RuntimeTypeAdapterFactory.of(BillingInstrument.class)
          .registerSubtype(CreditCard.class)
          .registerSubtype(BankTransfer.class);
    
      Gson gson = new GsonBuilder()
          .registerTypeAdapterFactory(billingAdapter)
          .create();
    
      // throws NullPointerException
      gson.toJson(new BillingInstrumentWrapper(null), BillingInstrumentWrapper.class);
    }

    static class BillingInstrumentWrapper {
      BillingInstrument instrument;
      BillingInstrumentWrapper(BillingInstrument instrument) {
        this.instrument = instrument;
      }
    }

Fails with the stacktrace:

    java.lang.NullPointerException
	at com.google.gson.typeadapters.RuntimeTypeAdapterFactory$1.write(RuntimeTypeAdapterFactory.java:218)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
	at com.google.gson.Gson.toJson(Gson.java:600)
	at com.google.gson.Gson.toJson(Gson.java:579)
	at com.google.gson.Gson.toJson(Gson.java:534)
	at com.google.gson.typeadapters.RuntimeTypeAdapterFactoryTest.testSerializeWrappedNullValue(RuntimeTypeAdapterFactoryTest.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:131)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

### PR DESCRIPTION
**Pull request by lcoote**

### CODE REVIEW

File: extras/src/test/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactoryTest.java [hunk 1]
```diff
@@ -167,6 +167,25 @@ public void testSerializeCollidingTypeFieldName() {
     }
   }
 
+  public void testSerializeWrappedNullValue() {
+    TypeAdapterFactory billingAdapter = RuntimeTypeAdapterFactory.of(BillingInstrument.class)
```
Comment (swankjesse) [inline extras/src/test/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactoryTest.java]: Would you ever get an instance of this via the public API?

Comment (swankjesse) [inline extras/src/test/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactoryTest.java]: Ie. can you reproduce this without importing code from our `internal` implementation details package?

Comment (lcoote) [inline extras/src/test/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactoryTest.java]: Which code from `internal` does my new test reference? The existing test code did import those packages but the test I have added does not (I believe).

Comment (swankjesse) [inline extras/src/test/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactoryTest.java]: RuntimeTypeAdapterFactory is not in Gson's public API. Can you demonstrate this problem using the public API only?

Comment (lcoote) [inline extras/src/test/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactoryTest.java]: I can't see how: this  IS a bug in `RuntimeTypeAdapterFactory`. Not in the GSON core.

As far as I understand, the `extras` package (where this class is located) is intended as a set of additional helper classes available for people to use, but it is distributed as source, I assume driven out of a desire to keep the GSON core light-weight. As far as I know, the compiled class is not packaged and distributed. I, as many others on the web have done, manually include and build the source ourselves in our own projects to make use of it.

(This is quite distinct from the `internal` package which includes source that is compiled, shipped and used to support the GSON core public API. However, it should not be called directly.)

So, in my use of `RuntimeTypeAdapterFactory` I have found the bug, fixed it and wish to share it with other people who use the class as well. Otherwise, what is this class for?

Comment (swankjesse) [inline extras/src/test/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactoryTest.java]: Ahhh, yes, yes good point. For whatever reason I was thinking that this class had been imported into Gson internal.

**Comment by swankjesse** [comment]
Thanks! And sorry for the hold-up.
