### PR TITLE
Fix DateFormat time zone is not restored and add Test.

### LINKED ISSUE #2547: `DateFormat` time zone is not restored after parsing, affecting subsequent serialization
# Gson version
2.10.1

# Java / Android version
Java 17

# Description
When deserializing a `java.util.Date` (and probably any of its subtypes) using a pattern with time zone, subsequent serialization using the same pattern is affected by it and uses the same time zone which was provided during deserialization. This can lead to undesired and unexpected behavior (e.g. one user can influence the date format of another user).

The underlying issue is that `DateFormat.parse` / `SimpleDateFormat.parse` can change the time zone of the instance, but does not restore it afterwards, see [JDK-6609675](https://bugs.openjdk.org/browse/JDK-6609675). So before any `parse` call it is necessary to obtain the time zone from the date format, then call `parse` and in a `finally` block restore the time zone again.
Based on the documentation it seems only the time zone is affected by this.

## Expected behavior
A call to `Gson.fromJson` should not affect subsequent `Gson.toJson` calls.

## Actual behavior
A call to `Gson.fromJson` can affect the output of subsequent `Gson.toJson` calls in case a date format which includes the time zone in the pattern is used.

# Reproduction steps
```java
TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd HH:mm z").create();
Date date = new Date(0);

// As expected: 1970-01-01 00:00 UTC
System.out.println(gson.toJson(date));

gson.fromJson("\"1970-01-01 00:00 PST\"", Date.class);

// Unexpected: 1969-12-31 16:00 PST
System.out.println(gson.toJson(date));
```

### PR DESCRIPTION
**Pull request by Carpe-Wang**
### Purpose
Fix DateFormat time zone is not restored after parsing. Fixes #2547
### Description
Before attempting to parse the date string, save the current timezone for each DateFormat object. Use a finally block to ensure that the original timezone is restored for each DateFormat object.

### Checklist

- [x] New code follows the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)\
  This is automatically checked by `mvn verify`, but can also be checked on its own using `mvn spotless:check`.\
  Style violations can be fixed using `mvn spotless:apply`; this can be done in a separate commit to verify that it did not cause undesired changes.
- [x] If necessary, new public API validates arguments, for example rejects `null`
- [x] New public API has Javadoc
    - [x] Javadoc uses `@since $next-version$`  
      (`$next-version$` is a special placeholder which is automatically replaced during release)
- [x] If necessary, new unit tests have been added  
  - [x] Assertions in unit tests use [Truth](https://truth.dev/), see existing tests
  - [x] No JUnit 3 features are used (such as extending class `TestCase`)
  - [x] If this pull request fixes a bug, a new test was added for a situation which failed previously and is now fixed
- [x] `mvn clean verify javadoc:jar` passes without errors

### CODE REVIEW

**Comment by Carpe-Wang** [comment]
I just fetch and pull the new code, and I use `mvn clean test -X`. there are some detailed error information as followed. 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project gson: Compilation failure: Compilation failure:
[ERROR] /Users/carpewang/googleDeveloper/gson/gson/src/main/java/module-info.java:[29,40] module not found: com.google.errorprone.annotations
[ERROR] Cannot access com.google.gson.module-info
[ERROR] Unable to resolve module
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project gson: Compilation failure

I try my best to solve the error, but I can't. could you help me in your spare time?

**Comment by Marcono1234** [comment]
Which JDK and Maven version are you using? Could you please provide the output of `mvn --version`?

**Comment by Carpe-Wang** [comment]
> Which JDK and Maven version are you using? Could you please provide the output of `mvn --version`?

Thank you for your reply. there is output of `mvn --version`
```
carpewang@bogon gson % mvn --version
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: /Users/carpewang/Desktop/apache-maven-3.9.5
Java version: 21.0.1, vendor: Oracle Corporation, runtime: /Users/carpewang/Library/Java/JavaVirtualMachines/openjdk-21.0.1/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "11.7.4", arch: "x86_64", family: "mac"
```

**Comment by Carpe-Wang** [comment]
> It looks like you are using JDK 21; could you please try JDK 17 instead? Gson currently does not support building with JDK 21, see #2501.

Hello, I'm encountering the same issue when I try to use JDK 17.
there is output of `mvn -- version`
```
carpewang@bogon gson % mvn --version    
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: /Users/carpewang/Desktop/apache-maven-3.9.5
Java version: 17.0.9, vendor: Amazon.com Inc., runtime: /Users/carpewang/Library/Java/JavaVirtualMachines/corretto-17.0.9/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "11.7.4", arch: "x86_64", family: "mac"
```

and there is error information when I run `mvn clean test -X`

```
[ERROR] /Users/carpewang/googleDeveloper/gson/gson/src/main/java/module-info.java:[29,40] module not found: com.google.errorprone.annotations
[ERROR] Cannot access com.google.gson.module-info
[ERROR] Unable to resolve module
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project gson: Compilation failure
```

**Comment by Carpe-Wang** [comment]
> It looks like you are using JDK 21; could you please try JDK 17 instead? Gson currently does not support building with JDK 21, see #2501.

ok, thank you for your help, I solve the error, and I am trying to do the picture which you mentioned before 
image

and add the test.

**Comment by Carpe-Wang** [comment]
> > It looks like you are using JDK 21; could you please try JDK 17 instead? Gson currently does not support building with JDK 21, see #2501.
> 
> ok, thank you for your help, I solve the error, and I am trying to do the picture which you mentioned before image
> 
> and add the test.

Hello, I had finished the `SqlTimeTypeAdapter` and `SqlDateTypeAdapter`. Please review the code.

File: gson/src/main/java/com/google/gson/internal/sql/SqlDateTypeAdapter.java [hunk 1]
```diff
@@ -62,7 +63,9 @@ public java.sql.Date read(JsonReader in) throws IOException {
     try {
       Date utilDate;
       synchronized (this) {
+        TimeZone originalTimeZone = format.getTimeZone(); // Save the original time zone
         utilDate = format.parse(s);
+        format.setTimeZone(originalTimeZone); // Restore the original time zone after parsing
```
Comment (Marcono1234) [inline gson/src/main/java/com/google/gson/internal/sql/SqlDateTypeAdapter.java:68]: Please use `try-finally` here as well, to be safe (in case time zone was already changed despite an exception being thrown):
```suggestion
        TimeZone originalTimeZone = format.getTimeZone(); // Save the original time zone
        try {
          utilDate = format.parse(s);
        } finally {
          format.setTimeZone(originalTimeZone); // Restore the original time zone after parsing
        }
```
(you might to have to reformat the code above)

File: gson/src/main/java/com/google/gson/internal/sql/SqlTimeTypeAdapter.java [hunk 2]
```diff
@@ -62,7 +63,9 @@ public Time read(JsonReader in) throws IOException {
     String s = in.nextString();
     try {
       synchronized (this) {
+        TimeZone originalTimeZone = format.getTimeZone(); // Save the original time zone
         Date date = format.parse(s);
+        format.setTimeZone(originalTimeZone); // Restore the original time zone
```
Comment (Marcono1234) [inline gson/src/main/java/com/google/gson/internal/sql/SqlTimeTypeAdapter.java:68]: Please use `try-finally` here as well:
```suggestion
        TimeZone originalTimeZone = format.getTimeZone(); // Save the original time zone
        try {
          date = format.parse(s);
        } finally {
          format.setTimeZone(originalTimeZone); // Restore the original time zone after parsing
        }
```
(you might to have to reformat the code above)

File: gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java [hunk 3]
```diff
@@ -223,6 +225,27 @@ public void testUnexpectedToken() throws Exception {
     }
   }
 
+  @Test
+  public void testGsonDateFormat() {
+    // Set the default timezone to UTC
+    TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
```
Comment (Marcono1234) [inline gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java:231]: Please restore the timezone in a `finally` block as well to not affect the other tests in any way, see for example how the `assertFormattingAlwaysEmitsUsLocale` method here does this.

File: gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java [hunk 4]
```diff
@@ -223,6 +225,27 @@ public void testUnexpectedToken() throws Exception {
...
+
+    // Serialize the date object
+    String json = gson.toJson(originalDate);
+    assertEquals("\"1970-01-01 00:00 UTC\"", json);
+
+    // Deserialize a date string with the PST timezone
+    Date deserializedDate = gson.fromJson("\"1970-01-01 00:00 PST\"", Date.class);
+
+    // Serialize the deserialized date object again
+    String jsonAfterDeserialization = gson.toJson(deserializedDate);
```
Comment (Marcono1234) [inline gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java:243]: Maybe this should rather call `toJson(originalDate)`; otherwise if `deserializedDate` is incorrect due to a bug we would get confusing failures here.

File: gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java [hunk 5]
```diff
@@ -223,6 +225,27 @@ public void testUnexpectedToken() throws Exception {
...
+    TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
+    Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd HH:mm z").create();
+    Date originalDate = new Date(0);
+
+    // Serialize the date object
+    String json = gson.toJson(originalDate);
+    assertEquals("\"1970-01-01 00:00 UTC\"", json);
+
+    // Deserialize a date string with the PST timezone
+    Date deserializedDate = gson.fromJson("\"1970-01-01 00:00 PST\"", Date.class);
```
Comment (Marcono1234) [inline gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java:240]: Maybe add an assertion here that the date was parsed correctly, I assume it would be this:
```suggestion
    Date deserializedDate = gson.fromJson("\"1970-01-01 00:00 PST\"", Date.class);
    assertThat(deserializedDate).isEqualTo(new Date(28800000));
```

File: gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java [hunk 6]
```diff
@@ -223,6 +225,27 @@ public void testUnexpectedToken() throws Exception {
...
+
+    // Serialize the deserialized date object again
+    String jsonAfterDeserialization = gson.toJson(deserializedDate);
+    // The expectation is that the date, after deserialization, when serialized again should still
+    // be in the UTC timezone
+    assertEquals("\"1970-01-01 08:00 UTC\"", jsonAfterDeserialization);
```
Comment (Marcono1234) [inline gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java:246]: Please use Truth instead of the JUnit methods here; that will leads to better failure messages and makes the assertion easier to read:
```suggestion
    assertThat(jsonAfterDeserialization).isEqualTo("\"1970-01-01 08:00 UTC\"");
```

**Review by Marcono1234 — COMMENTED** [review]
Thanks a lot! I have added a few small review comments but generally at least to me this PR looks good.

**Comment by Marcono1234** [comment]
One more thing: Could you please edit the description to say "Fixes #2547" instead of "About issue is #2547".
GitHub will then link this PR to the issue (shown on the right under "Successfully merging this pull request may close these issues"), and once this PR is merged will automatically close the issue as well.

Just in case you didn't know this, you can edit the description of the PR by clicking the "..." at the top right:
GitHub PR description button screenshot

**Comment by Carpe-Wang** [comment]
> Thanks a lot! I have added a few small review comments but generally at least to me this PR looks good.

thanks I had change the pr description, and add `try finally ` in `DefaultDateTypeAdapterTest`, `SqlTimeTypeAdapter`, and `SqlDateTypeAdapter`. But I meet some troubles when I want change testGsonDateFormat in DefaultDateTypeAdapterTest.  Gson BUILD FAILURE because of 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project gson: Compilation failure
[ERROR] Warnings found, but -Werror was specified
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project gson: Compilation failure
Warnings found, but -Werror was specified
```

File: gson/src/main/java/com/google/gson/internal/sql/SqlDateTypeAdapter.java [hunk 7]
```diff
@@ -60,17 +60,18 @@ public java.sql.Date read(JsonReader in) throws IOException {
       return null;
     }
     String s = in.nextString();
+    TimeZone originalTimeZone = format.getTimeZone(); // Save the original time zone
```
Comment (Marcono1234) [inline gson/src/main/java/com/google/gson/internal/sql/SqlDateTypeAdapter.java:63]: Please move this and the `setTimeZone` call inside the `synchronized (this) { ... }` block. Type adapters must be thread-safe and with the current implementation there could be a race condition.

Or better, rewrite this so that the `synchronized` block covers the `try`; I guess that should be fine as well, e.g.:
```java
    synchronized (this) {
      TimeZone originalTimeZone = format.getTimeZone(); // Save the original time zone
      try {
        Date utilDate = format.parse(s);
        return new java.sql.Date(utilDate.getTime());
      } catch (ParseException e) {
        throw new JsonSyntaxException("Failed parsing '" + s + "' as SQL Date; at path " + in.getPreviousPath(), e);
      } finally {
        format.setTimeZone(originalTimeZone); // Restore the original time zone after parsing
      }
    }
```

File: gson/src/main/java/com/google/gson/internal/sql/SqlTimeTypeAdapter.java [hunk 8]
```diff
@@ -61,16 +61,17 @@ public Time read(JsonReader in) throws IOException {
       return null;
     }
     String s = in.nextString();
+    TimeZone originalTimeZone = format.getTimeZone(); // Save the original time zone
```
Comment (Marcono1234) [inline gson/src/main/java/com/google/gson/internal/sql/SqlTimeTypeAdapter.java:64]: Same as in:

**Comment by Marcono1234** [comment]
> But I meet some troubles when I want change testGsonDateFormat in DefaultDateTypeAdapterTest. Gson BUILD FAILURE because of
> ```
> Warnings found, but -Werror was specified
> ```

You have to look further up in the Maven log output then; there should be one or more "[WARNING] ..." lines for the maven-compiler-plugin. Alternatively, you can also push the non-working code if you want so that we can see the error message here in the GitHub workflow log, and suggest how to solve it.

File: gson/src/main/java/com/google/gson/internal/sql/SqlDateTypeAdapter.java (hunk 7 above)
Comment (Carpe-Wang) [reply gson/src/main/java/com/google/gson/internal/sql/SqlDateTypeAdapter.java]: This is my mistake; I did not carefully read the code review you provided at the beginning.

**Comment by Carpe-Wang** [comment]
> Date deserializedDate = gson.

I solved it. Thank you for your patient replys. I believe that the suggestion in the image to use toJson(originalDate) is unnecessary because I have already performed toJson on both originalDate and deserializedDate, with corresponding assertions for each.
image

File: gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java [hunk 9]
```diff
@@ -223,6 +225,36 @@ public void testUnexpectedToken() throws Exception {
...
+      // Assert that the deserialized date's time is correct
+      assertThat(deserializedDate.getTime()).isEqualTo(new Date(28800000).getTime());
+
+      // Serialize the deserialized date object again
+      String jsonAfterDeserialization = gson.toJson(deserializedDate);
+      // The expectation is that the date, after deserialization, when serialized again should still
+      // be in the UTC timezone
+      Date expectedDate = new Date(28800000); // This represents the original date in UTC
+      String expectedJson = gson.toJson(expectedDate);
+      assertThat(jsonAfterDeserialization).isEqualTo(expectedJson);
```
Comment (Marcono1234) [inline gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java:252]: Please hardcode the expected JSON string here:
```suggestion
      assertThat(jsonAfterDeserialization).isEqualTo("\"1970-01-01 08:00 UTC\"");
```

Otherwise your current code would fail to detect the bug (if you reverted your `setTimeZone` fix) because both `gson.toJson(deserializedDate)` and `gson.toJson(expectedDate)` would use PST as time zone, and would therefore both be wrong. But because both are wrong in the same way, the test would erroneously pass as successful.

File: gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java [hunk 10]
```diff
@@ -223,6 +225,36 @@ public void testUnexpectedToken() throws Exception {
...
+    TimeZone originalTimeZone = TimeZone.getDefault();
+    // Set the default timezone to UTC
+    TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
+    try {
+      Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd HH:mm z").create();
+      Date originalDate = new Date(0);
+
+      // Serialize the date object
+      String json = gson.toJson(originalDate);
+      assertEquals("\"1970-01-01 00:00 UTC\"", json);
```
Comment (Marcono1234) [inline gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java:239]: Please use Truth for assertions here:
```suggestion
      assertThat(json).isEqualTo("\"1970-01-01 00:00 UTC\"");
```

**Review by Marcono1234 — COMMENTED** [review]
> I believe that the suggestion in the image to use toJson(originalDate) is unnecessary because I have already performed toJson on both originalDate and deserializedDate, with corresponding assertions for each.

Ok, that is fine for me now because you added `assertThat(deserializedDate.getTime()).isEqualTo(...)`.

Just two more small things, see comments.

**Comment by Carpe-Wang** [comment]
> > I believe that the suggestion in the image to use toJson(originalDate) is unnecessary because I have already performed toJson on both originalDate and deserializedDate, with corresponding assertions for each.
> 
> Ok, that is fine for me now because you added `assertThat(deserializedDate.getTime()).isEqualTo(...)`.
> 
> Just two more small things, see comments.

Thank you for your suggestions; they are helpful for improving my skills. I have made the changes according to your comments.

**Review by Marcono1234 — APPROVED** [review]
Thanks for your work on this! The changes look good to me.
@eamonnmcmanus, could you please have a look?

---

Just one small note, but you don't have to change the code for that:
I thought a bit more about the `gson.toJson(deserializedDate)` in the test. This bothers me a bit because the point is that the time zone _of the `DateFormat`_ is not restored. The current test code makes it look a bit as if `Date` internally stored a time zone as well (which it doesn't), and as if the `DateFormat` 'forces' usage of UTC even though the `Date` has PST as time zone (again, which is not actually the case).
That is why I think it would have been a bit cleaner to call `gson.toJson(originalDate)` a second time instead of `gson.toJson(deserializedDate)`, because that makes it clearer that the issue here is with the `DateFormat`, and not with the deserialized `Date`.

**Comment by Carpe-Wang** [comment]
> Thanks for your work on this! The changes look good to me. @eamonnmcmanus, could you please have a look?
> 
> Just one small note, but you don't have to change the code for that: I thought a bit more about the `gson.toJson(deserializedDate)` in the test. This bothers me a bit because the point is that the time zone _of the `DateFormat`_ is not restored. The current test code makes it look a bit as if `Date` internally stored a time zone as well (which it doesn't), and as if the `DateFormat` 'forces' usage of UTC even though the `Date` has PST as time zone (again, which is not actually the case). That is why I think it would have been better to call `gson.toJson(originalDate)` a second time instead of `gson.toJson(deserializedDate)`, because that makes it clearer that the issue here is with the `DateFormat`, and not with the deserialized `Date`.

Thank you for your patient guide which is valuable for me.

**Comment by Carpe-Wang** [comment]
Hello @eamonnmcmanus, if there are any changes that you are still dissatisfied with, or if you think there are areas that can be improved, please let me know.

**Review by eamonnmcmanus — APPROVED** [review]
Thanks for doing this! And sorry it took me a while to get to it.

File: gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java (hunk 4 above)
Comment (stefanajons) [reply gson/src/test/java/com/google/gson/internal/bind/DefaultDateTypeAdapterTest.java]: Hyt
