### PR TITLE
Prevent `TypeToken` from capturing type variables

### LINKED ISSUE #1219: Don't silently ignore missing type information from `TypeTokens`.
I'm active on Stack Overflow, and often see questions with code more or less like this:

```
public class Main {
		
	public static void main(String[] args) {
            // should work right?
	    MyClass mc = new Gson().fromJson("{}", Main.<MyClass>typeTokenHelper());
	}
	
	static class MyClass {}
	
	public static <T> Type typeTokenHelper() {
		return new TypeToken<T>() {}.getType();
	}

}
```

Of course this fails with:

```
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to test.Main$MyClass
```

Since there is not actually any type information available from the `TypeToken`. The `Type` that you get is the generic type `T`:

```
Type t = Main.<MyClass>typeTokenHelper();
System.out.println(t); // prints 'T'. instead of the naïvely expected 'MyClass'
```

This is confusing. The missing type information should not be silently ignored only to get a `ClassCastException` later. The missing type information is caused by a design time error and should be flagged as early as possible.

At first glance a check like this:

```
// where 'typeOfT' is the type returned by TypeToken::getType
if(typeOfT instanceof TypeVariable) {  // java.lang.reflect.TypeVariable
    throw new RuntimeExcepiton(...);
}
```

Somewhere might fix this issue. Perhaps in [`TypeToken::getSuperclassTypeParameter`](https://github.com/google/gson/blob/0636635cbffa08157bdbd558b1212e4d806474eb/gson/src/main/java/com/google/gson/reflect/TypeToken.java#L81) or in [`Gson::fromJson`](https://github.com/google/gson/blob/0636635cbffa08157bdbd558b1212e4d806474eb/gson/src/main/java/com/google/gson/Gson.java#L878). (I don't know where the use of TypeTokens with TypeVariables might be required though)

### PR DESCRIPTION
**Pull request by Marcono1234**
~~:warning: Depends on #2375~~

### Purpose
Fixes #1219

### Description
Throws an exception when the user tries to capture a type variable using `new TypeToken<...>() {}`, see #1219. This is extremely error-prone because at compile time such code looks safe, but at runtime it leads to confusing `ClassCastException`s due to type erasure; and users keep running into this issue (see https://github.com/google/gson/issues/1219#issuecomment-1445381429).

The exception message which is thrown refers to a new troubleshooting guide section which describes possible workarounds. Additionally for now an opt-in system property is added which allows capturing type variables again.

### Checklist

- [x] New code follows the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)
- [x] If necessary, new public API validates arguments, for example rejects `null`
- [ ] New public API has Javadoc
    - [ ] Javadoc uses `@since $next-version$`  
      (`$next-version$` is a special placeholder which is automatically replaced during release)
- [x] If necessary, new unit tests have been added  
  - [x] Assertions in unit tests use [Truth](https://truth.dev/), see existing tests
  - [x] No JUnit 3 features are used (such as extending class `TestCase`)
  - [x] If this pull request fixes a bug, a new test was added for a situation which failed previously and is now fixed
- [x] `mvn clean verify javadoc:jar` passes without errors

### CODE REVIEW

File: gson/src/main/java/com/google/gson/reflect/TypeToken.java [hunk 1]
```diff
@@ -92,19 +107,57 @@ private Type getTypeTokenTypeArgument() {
...
+      for (Type bound : wildcardType.getLowerBounds()) {
+        verifyNoTypeVariable(bound);
+      }
+      for (Type bound : wildcardType.getUpperBounds()) {
+        verifyNoTypeVariable(bound);
+      }
+    } else if (type == null) {
+      // Occurs in Eclipse IDE and certain Java versions (e.g. Java 11.0.18) when capturing type variable
+      // declared by method of local class, see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/975
+      throw new IllegalArgumentException("TypeToken captured `null` as type argument; probably a compiler / runtime bug");
```
Comment (Marcono1234) [inline gson/src/main/java/com/google/gson/reflect/TypeToken.java:157]: This is quite an interesting bug, which even occurred even on CI when running with JDK 11, so in the corresponding unit tests it checks for this exception message as well.

See also https://github.com/eclipse-jdt/eclipse.jdt.core/issues/975

File: Troubleshooting.md [hunk 2]
```diff
@@ -17,7 +17,7 @@ This guide describes how to troubleshoot common issues when using Gson.
...
+- When using `TypeToken` make sure you don't capture a type variable. For example avoid something like `new TypeToken<List<T>>()` (where `T` is a type variable). Due to Java [type erasure](https://dev.java/learn/generics/type-erasure/) the actual type of `T` is not available at runtime. Refactor your code to pass around `TypeToken` instances or use [`TypeToken.getParameterized(...)`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html#getParameterized(java.lang.reflect.Type,java.lang.reflect.Type...)), for example `TypeToken.getParameterized(List.class, elementType)` where `elementType` is a type you have to provide separately.
```
Comment (Marcono1234) [inline Troubleshooting.md:20]: Refers to https://dev.java here and below because that page contains a good explanation, and also this seems to be the official Java website, even though it is probably not that well known yet because it is still quite new.

File: Troubleshooting.md [hunk 3]
```diff
@@ -281,3 +281,23 @@ Class.forName(jsonString, false, getClass().getClassLoader()).asSubclass(MyBaseC
...
+
+Note: Earlier version of Gson unfortunately did not prevent capturing type variables, which caused many users to unwittingly write type unsafe code.
+
+**Solution:**
+
+- Use [`TypeToken.getParameterized(...)`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html#getParameterized(java.lang.reflect.Type,java.lang.reflect.Type...)), for example `TypeToken.getParameterized(List.class, elementType)` where `elementType` is a type you have to provide separately.
+- For Kotlin users: Use [`reified` type parameters](https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters), that means change `<T>` to `<reified T>`, if possible. If you have a chain of functions with type parameters you will probably have to make all of them `reified`.
+- If you don't actually use Gson's `TypeToken` for any Gson method, use a general purpose 'type token' implementation provided by a different library instead, for example Guava's [`com.google.common.reflect.TypeToken`](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/reflect/TypeToken.html).
```
Comment (Marcono1234) [inline Troubleshooting.md:297]: I am not completely sure to what extent the Guava `TypeToken` actually wants to support capturing type variables. For example `new TypeToken<T>() {}` [throws an exception](https://github.com/google/guava/blob/0a17f4a429323589396c38d8ce75ca058faa6c64/guava/src/com/google/common/reflect/TypeToken.java#L127-L132). However creating `TypeToken<List<T>>` and similar works. Similarly the [wiki](https://github.com/google/guava/wiki/ReflectionExplained#typetoken) says that "it supports non-reified types such as `T`, `List<T>`", so support for type variables seems to be at least to some extent intended.

**Comment by Marcono1234** [comment]
@eamonnmcmanus, what is your position on this? Your comment https://github.com/google/gson/issues/1219#issuecomment-1456319866 sounded to me as if you are generally open to adding this restriction eventually, but maybe I misunderstood it. The solution proposed here does not differentiate between serialization and deserialization, it blocks usage of type variables for `TypeToken` in general.

Depending on that I will try to resolve the merge conflicts in the near future.

**Comment by eamonnmcmanus** [comment]
> @eamonnmcmanus, what is your position on this? Your comment [#1219 (comment)](https://github.com/google/gson/issues/1219#issuecomment-1456319866) sounded to me as if you are generally open to adding this restriction eventually, but maybe I misunderstood it. The solution proposed here does not differentiate between serialization and deserialization, it blocks usage of type variables for `TypeToken` in general.

OK, a few things. I commented on #2375 separately and I think we can probably make that work with the small change I suggested.

I ran this change against all of Google's internal tests and encountered one failure. The class looks like this in outline:
```java
public abstract class AbstractAction<D extends Dto, T extends Service<D>> implements Action {
  ...
  private final Type listType = new TypeToken<List<D>>() {}.getType();
  ...
   return new SafeJsonResponse(GSON, result, listType);
```

So, even though Gson is in the picture, here `TypeToken` is just being used to get a `Type` for `List<D>`. However, that `Type` does later get used for `gson.toJson(object, type)` inside `SafeJsonResponse`.

I naively tried to fix the new exception by writing `new TypeToken<List<? extends Dto>>` but that didn't work. A test failure suggests that the JSON serialization was different. I didn't track down why. `new TypeToken<List<Dto>>` does work. I mention that because it suggests that fixing code to avoid the new exception may not be completely trivial. (In fact I see that I already changed this code to `? extends Dto` last year but that change was reverted. The test failure I saw didn't exist then but presumably the serialization difference did.)

Just one problem out of tens of thousands of files referencing Gson is a pretty low rate, and needs to be balanced against the many issues you found on StackOverflow. So I think we probably _could_ control this with a system property. For example the class I cited could have a static intializer that sets the property.

I think this would be the first time we introduce a system property into the Gson code, so we would need to decide on a naming convention. Unfortunately system property names are all over the place, but using dashes does seem to be somewhat unusual. I've never been very happy with the likes of `com.google.gson.words.separated.by.dots` either. I think maybe the least-bad option is to use something that looks like a class name, for example `com.google.gson.AllowCapturingTypeVariables` or `gson.AllowCapturingTypeVariables`.

**Comment by Marcono1234** [comment]
Thanks for taking a look and thanks for the feedback on this!

> I naively tried to fix the new exception by writing `new TypeToken<List<? extends Dto>>` but that didn't work.

Might be #1870; for `WildcardType` the runtime type is not used so that could make a difference in the JSON output. Or the reason could be that the `Collection` and `Map` type resolution logic does not use the upper bounds for wildcards, the `Map` resolution logic [has a tentative TODO comment for that](https://github.com/google/gson/blob/9cf0f8d3022fdfcd480dcd7648b2e5209e775b52/gson/src/main/java/com/google/gson/internal/%24Gson%24Types.java#L333).

> I mention that because it suggests that fixing code to avoid the new exception may not be completely trivial

In this specific case, if you have `Class<D>` available within `AbstractAction`, maybe you could use `TypeToken.getParameterized(List.class, classOfD)` to create `listType`?


> I think this would be the first time we introduce a system property into the Gson code, so we would need to decide on a naming convention. Unfortunately system property names are all over the place, but using dashes does seem to be somewhat unusual. I've never been very happy with the likes of `com.google.gson.words.separated.by.dots` either. I think maybe the least-bad option is to use something that looks like a class name, for example `com.google.gson.AllowCapturingTypeVariables` or `gson.AllowCapturingTypeVariables`.

Good point! If we use a naming which looks like a package or class name, then we could also use the qualified class name of `TypeToken` and append a 'fake' field name, for example something like `com.google.gson.reflect.TypeToken.allowCapturingTypeVariables`. Though that might be a bit verbose. What do you think?

Your shorter suggestions also sound good, but I think it would be better to lowercase the first `a` of `AllowCa...`. Otherwise it looking like a class name might rather cause confusion, because if I recall correctly sometimes system properties do actually have the name of a class for example when the user can specify a concrete implementation for that class.

**Comment by Marcono1234** [comment]
Rebased the changes onto `main`, now after #2375 has been merged (thanks for that!). But to avoid any misunderstanding, I think your question about naming the system property is still open.

**Comment by Marcono1234** [comment]
Would using `gson.allowCapturingTypeVariables` (with lowercase `a`) as system property name be fine for you?

**Comment by eamonnmcmanus** [comment]
> Would using `gson.allowCapturingTypeVariables` (with lowercase `a`) as system property name be fine for you?

Yes, I think the convention that that establishes looks good.

**Comment by Marcono1234** [comment]
@eamonnmcmanus, do you think this can be merged?

In the worst case, if this is really causing more issues than it helps preventing bugs, we could revert it again in a future release. Since this only adds validation but does not introduce any new feature or alters Gson behavior in any other way, reverting the changes should be safe.

File: gson/src/main/java/com/google/gson/reflect/TypeToken.java [hunk 4]
```diff
@@ -83,6 +92,11 @@ private TypeToken(Type type) {
     this.hashCode = this.type.hashCode();
   }
 
+  private static boolean isCapturingTypeVariablesForbidden() {
+    String value = System.getProperty("gson.allowCapturingTypeVariables");
```
Comment (eamonnmcmanus) [inline gson/src/main/java/com/google/gson/reflect/TypeToken.java:96]: I think we could do this?
```
return !Objects.equals(System.getProperty(...), "true");
```

**Review by eamonnmcmanus — CHANGES_REQUESTED** [review]
Sorry for the delay. I think we can go ahead with this. Just one small change requested.

**Review by eamonnmcmanus — APPROVED** [review]
